name: nima
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.13.0+2
  frino_icons: ^1.0.1+4
  flutter_rating_bar: ^4.0.0
  provider: ^5.0.0
  google_maps_flutter: ^2.0.3
  location: ^4.1.1
  geoflutterfire: ^2.0.0
  cloud_firestore: ^0.9.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/langs/fr.json
    - assets/langs/ar.json
