name: nima
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_place_picker: 2.0.0-nullsafety.3
  http: ^0.13.0+2
  frino_icons: ^1.0.1+4
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/langs/fr.json
    - assets/langs/ar.json
